HOTELS_TO_SCRAPE = [
    {'property_code': 'AHNRZ', 'name': 'Ritz Carlton Lake Oconee', 'city': 'Lake Oconee, GA'},
    {'property_code': 'ATLRZ', 'name': 'Ritz Carlton, Atlanta', 'city': 'Atlanta, GA'},
    {'property_code': 'ATLBK', 'name': 'Ritz Carlton, Buckhead', 'city': 'Atlanta, GA'},
    {'property_code': 'ATLJW', 'name': 'JW Marriott Atlanta Buckhead', 'city': 'Atlanta, GA'},
    {'property_code': 'RNORZ', 'name': 'The Ritz-Carlton, Lake Tahoe', 'city': 'Lake Tahoe, CA'},
]
US_RITZ_HOTELS = [
    {'property_code': 'JAXAM', 'name': 'The Ritz-Carlton, Amelia Island', 'city': 'Amelia Island, FL'},
    {'property_code': 'WASPC', 'name': 'The Ritz-Carlton, Pentagon City', 'city': 'Arlington, VA'},
    {'property_code': 'ATLRZ', 'name': 'The Ritz-Carlton, Atlanta', 'city': 'Atlanta, GA'}
    {'property_code': 'ATLBK', 'name': 'The Ritz-Carlton, Buckhead', 'city': 'Atlanta, GA'},
    {'property_code': 'WHRRZ', 'name': 'The Ritz-Carlton, Bachelor Gulch', 'city': 'Avon, CO'},
    {'property_code': 'MIAZL', 'name': 'The Ritz-Carlton Bal Harbour, Miami', 'city': 'Bal Harbour, FL'},
    {'property_code': 'BOSRT', 'name': 'The Ritz-Carlton, Boston', 'city': 'Boston, MA'},
    {'property_code': 'CLTRZ', 'name': 'The Ritz-Carlton, Charlotte', 'city': 'Charlotte, NC'},
    {'property_code': 'CHIRZ', 'name': 'The Ritz-Carlton, Chicago', 'city': 'Chicago, IL'},
    {'property_code': 'CLERZ', 'name': 'The Ritz-Carlton, Cleveland', 'city': 'Cleveland, OH'},
    {'property_code': 'DALRZ', 'name': 'The Ritz-Carlton, Dallas', 'city': 'Dallas, TX'},
    {'property_code': 'SNARZ', 'name': 'The Ritz-Carlton, Laguna Niguel', 'city': 'Dana Point, CA'},
    {'property_code': 'DENRZ', 'name': 'The Ritz-Carlton, Denver', 'city': 'Denver, CO'},
    {'property_code': 'FLLRZ', 'name': 'The Ritz-Carlton, Fort Lauderdale', 'city': 'Fort Lauderdale, FL'},
    {'property_code': 'AHNRZ', 'name': 'The Ritz-Carlton Reynolds, Lake Oconee', 'city': 'Greensboro, GA'},
    {'property_code': 'HAFRZ', 'name': 'The Ritz-Carlton, Half Moon Bay', 'city': 'Half Moon Bay, CA'},
    {'property_code': 'JHMRZ', 'name': 'The Ritz-Carlton, Kapalua', 'city': 'Kapalua, HI'},
    {'property_code': 'MIAKB', 'name': 'The Ritz-Carlton Key Biscayne, Miami', 'city': 'Key Biscayne, FL'},
    {'property_code': 'LAXLZ', 'name': 'The Ritz-Carlton, Los Angeles', 'city': 'Los Angeles, CA'},
    {'property_code': 'TUSRZ', 'name': 'The Ritz-Carlton, Dove Mountain', 'city': 'Marana, AZ'},
    {'property_code': 'LAXMD', 'name': 'The Ritz-Carlton, Marina del Rey', 'city': 'Marina del Rey, CA'},
    {'property_code': 'WASTY', 'name': 'The Ritz-Carlton, Tysons Corner', 'city': 'McLean, VA'},
    {'property_code': 'MIAEB', 'name': 'The Miami Beach EDITION', 'city': 'Miami Beach, FL'},
    {'property_code': 'MIASB', 'name': 'The Ritz-Carlton, South Beach', 'city': 'Miami Beach, FL'},
    {'property_code': 'MIARZ', 'name': 'The Ritz-Carlton Coconut Grove, Miami', 'city': 'Miami, FL'},
    {'property_code': 'YULRM', 'name': 'Ritz-Carlton, Montréal', 'city': 'Montréal, Canada'},
    {'property_code': 'RSWGR', 'name': 'The Ritz-Carlton Golf Resort, Naples', 'city': 'Naples, FL'},
    {'property_code': 'RSWRZ', 'name': 'The Ritz-Carlton, Naples', 'city': 'Naples, FL'},
    {'property_code': 'MSYRZ', 'name': 'The Ritz-Carlton, New Orleans', 'city': 'New Orleans, LA'},
    {'property_code': 'NYCEB', 'name': 'The New York EDITION', 'city': 'New York, NY'},
    {'property_code': 'NYCRD', 'name': 'The Ritz-Carlton New York, Battery Park', 'city': 'New York, NY'},
    {'property_code': 'NYCCP', 'name': 'The Ritz-Carlton New York, Central Park', 'city': 'New York, NY'},
    {'property_code': 'MCORZ', 'name': 'The Ritz-Carlton, Orlando, Grande Lakes', 'city': 'Orlando, FL'},
    {'property_code': 'PHLRT', 'name': 'The Ritz-Carlton, Philadelphia', 'city': 'Philadelphia, PA'},
    {'property_code': 'PSPPS', 'name': 'The Ritz-Carlton, Rancho Mirage', 'city': 'Rancho Mirage, CA'},
    {'property_code': 'SFORZ', 'name': 'The Ritz-Carlton, San Francisco', 'city': 'San Francisco, CA'},
    {'property_code': 'SRQRZ', 'name': 'The Ritz-Carlton, Sarasota', 'city': 'Sarasota, FL'},
    {'property_code': 'STLRZ', 'name': 'The Ritz-Carlton, St. Louis', 'city': 'St. Louis, MO'},
    {'property_code': 'YYZRZ', 'name': 'The Ritz-Carlton, Toronto', 'city': 'Toronto, Canada'},
    {'property_code': 'RNORZ', 'name': 'The Ritz-Carlton, Lake Tahoe', 'city': 'Truckee, CA'},
    {'property_code': 'WHRLH', 'name': 'The Ritz Carlton Club, Vail', 'city': 'Vail, CO'},
    {'property_code': 'HNLRR', 'name': 'The Ritz-Carlton Residences, Waikiki Beach', 'city': 'Waikiki Beach, HI'},
    {'property_code': 'WASGO', 'name': 'The Ritz-Carlton Georgetown, Washington, D.C.', 'city': 'Washington, DC'},
    {'property_code': 'WASRT', 'name': 'The Ritz-Carlton, Washington, D.C.', 'city': 'Washington, DC'},
    {'property_code': 'NYCRW', 'name': 'The Ritz-Carlton New York, Westchester', 'city': 'White Plains, NY'}
]