"""moved zip to different table

Revision ID: 62afade57ded
Revises: c5ad1d417adc
Create Date: 2016-12-15 20:03:35.325208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62afade57ded'
down_revision = 'c5ad1d417adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'zip_code')
    op.add_column('locations', sa.Column('zip_code', sa.String(length=5), nullable=True))
    op.drop_column('locations', 'per_diem_rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('per_diem_rate', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
    op.drop_column('locations', 'zip_code')
    op.add_column('hotels', sa.Column('zip_code', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
