"""added zip code

Revision ID: c5ad1d417adc
Revises: 
Create Date: 2016-12-15 19:49:49.183848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ad1d417adc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('per_diem_rates')
    op.add_column('hotels', sa.Column('zip_code', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'zip_code')
    op.create_table('per_diem_rates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('locality', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('county', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('season_begin', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('season_end', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('max_lodging', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('local_meals', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('proportional_meals', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('max_per_diem_rate', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('effective_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='per_diem_rates_pkey')
    )
    # ### end Alembic commands ###
